#!/usr/bin/env node
const argv = require('yargs');
const axios = require('axios');

// demand an array of keys to be provided
argv.version('1.1.0');

argv.command({
  command: 'add',
  describe: 'Add new todo',
  aliases: ['a'],
  builder: {
    title: {
      describe: 'Todo title',
      demandOption: true,
      type: 'string',
      alias: 't',
    },
    description: {
      describe: 'Description of todo',
      demandOption: true,
      type: 'string',
      alias: 'd',
    },
    done: {
      describe: 'Status of todo',
      demandOption: false,
      type: 'boolean',
      default: false,
    },
  },
  strict: true,
  handler: function(argv) {
    console.log('Title: ' + argv.title);
    console.log('Body: ' + argv.description);
    console.log('Done: ' + argv.done);
  },
});
argv.command({
  command: 'list',
  aliases: ['l'],
  desc: 'List all todos',
  strict: true,
  handler: argv => {
    console.log(`Listando todas as tarefas`);
  },
});
argv.command({
  command: 'search [id]',
  aliases: ['s'],
  desc: 'Search todo by id',
  strict: true,
  handler: argv => {
    console.log(`Buscando tarefa x`);
  },
});
argv.command({
  command: 'update [id]',
  describe: 'Update new todo',
  aliases: ['u'],
  builder: {
    id: {
      describe: 'Todo title',
      demandOption: true,
      type: 'string',
      alias: 'tasd',
    },
    title: {
      describe: 'Todo title',
      demandOption: false,
      type: 'string',
      alias: 't',
    },
    description: {
      describe: 'Description of todo',
      demandOption: false,
      type: 'string',
      alias: 'd',
    },
    done: {
      describe: 'Status of todo',
      demandOption: false,
      type: 'boolean',
      default: false,
    },
  },
  handler: function(argv) {
    console.log('Title: ' + argv.title);
    console.log('Body: ' + argv.description);
    console.log('Done: ' + argv.done);
  },
});
argv.command({
  command: 'delete [id]',
  aliases: ['d'],
  desc: 'Delete todo by id',
  handler: argv => {
    console.log(`Apagando tarefa x`);
  },
  strict: true,
});

argv
  .help()
  .locale('en')
  .alias('help', 'h')
  .alias('version', 'v')
  .demandCommand(1, 'Você deve selecionar no mínimo um comando para continuar')
  .showHelpOnFail(true)
  .strict()
  .recommendCommands().argv;
